In [1]:
import numpy

vetor = numpy.array([1, -3, 4.2, 5])

In [2]:
type(vetor)

numpy.ndarray

In [4]:
print(vetor)
print(vetor[0])
print(vetor[1])

[ 1.  -3.   4.2  5. ]
1.0
-3.0


In [5]:
# criar uma matriz no formato array com 2 linhas e 3 colunas
# matriz de 2L x 3C
#  .ones(preenche com o número 1)
matriz = numpy.ones((2, 3))
print(type(matriz))
print(matriz)

<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# valores do array preenchem de uma diagonal a outra da matriz
# matriz 5l X 5c
matriz_diagonal = numpy.diag((2, 4, 6, 8, 10))
print(matriz_diagonal)

[[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]
