In [48]:
import numpy
import pandas

# POPULAÇÃO:
data6 = pandas.read_csv("csv/04-classificados_tratado.csv", sep=",", encoding="iso-8859-1")
data6.shape

(81231, 28)

In [49]:
# AMOSTRAGEM: Cidade de Campinas
campinas = data6.loc[data6.NO_MUNICIPIO_RESIDENCIA == "Campinas"]
campinas.shape

(1982, 28)

In [50]:
# pegar um número aleatório de início de 0 até 10, 1 - quant. de números que vai pegar.
# se mudar o num. do seed muda o array de índece
numpy.random.seed(1)
begin = numpy.random.choice(10, 1)
begin

array([3])

In [51]:
# AMOSTRAGEM SISTEMATICA: (Ordena EL numericamente / seleciona aleatoriamente usando uma seq. numerica)
# criar um array de índice dos EL que serão capturados
# (Valor inicial, valor max, e valor de salto de x em x )
array_numeros_amostras = numpy.arange(begin, 1982, 100)
array_numeros_amostras

array([   3,  103,  203,  303,  403,  503,  603,  703,  803,  903, 1003,
       1103, 1203, 1303, 1403, 1503, 1603, 1703, 1803, 1903])

In [52]:
# iloc (i de índice) / : (se refere a a todas as colunas)
amostra_sistematica = campinas.iloc[array_numeros_amostras,:]
amostra_sistematica.shape

(20, 28)

In [54]:
amostra_sistematica.head(2)

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  IDADE SEXO  TP_ESTADO_CIVIL  \
304      1,90E+11                Campinas     17    M                1   
5364     1,90E+11                Campinas     18    M                2   

        RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA  CO_ESCOLA  \
304   branca                 1                3  não_respondeu        NaN   
5364   parda                 1                3  não_respondeu        NaN   

      ...  NOTA_MT  TP_LINGUA  TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  \
304   ...    745.3     Inglês                1.0  160.0  200.0  180.0  200.0   
5364  ...    601.1     Inglês                1.0  120.0  140.0  120.0  100.0   

      COMP5  NOTA_REDACAO INTERNET  
304   140.0         880.0      Sim  
5364   80.0         560.0      Sim  

[2 rows x 28 columns]

In [56]:
# C/ Salto aleatório:
numpy.random.seed(2)
# begin (pegar um número aleatório de início de 0 até 10, e quant. de números que vai pegar "1")
# jump (Valor salto aleatório, saltar entre 100 e 150, e quant. de números que vai pegar "1" )

begin = numpy.random.choice(10, 1)
jump = numpy.random.randint(100, 150, 1)
print(begin, jump)

[8] [115]


In [60]:
array_numeros_amostras = numpy.arange(begin, 1982, jump)
array_numeros_amostras

array([   8,  123,  238,  353,  468,  583,  698,  813,  928, 1043, 1158,
       1273, 1388, 1503, 1618, 1733, 1848, 1963])

In [63]:
amostra_sistematica_2 = campinas.iloc[array_numeros_amostras, :]
amostra_sistematica_2.shape

(18, 28)

In [65]:
amostra_sistematica_2.head(2)

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  IDADE SEXO  TP_ESTADO_CIVIL  \
508      1,90E+11                Campinas     16    F                1   
6351     1,90E+11                Campinas     16    F                1   

        RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA  CO_ESCOLA  \
508   branca                 1                3  não_respondeu        NaN   
6351  branca                 1                3  não_respondeu        NaN   

      ...  NOTA_MT  TP_LINGUA  TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  \
508   ...     71.1     Inglês                1.0  160.0  120.0  140.0  160.0   
6351  ...    672.9     Inglês                1.0  160.0  180.0  180.0  180.0   

      COMP5  NOTA_REDACAO INTERNET  
508   180.0         760.0      Sim  
6351  200.0         900.0      Sim  

[2 rows x 28 columns]

In [67]:
amostra_sistematica.to_csv("csv/06-amostra_sistematica.csv", encoding="iso-8859-1", index=False)
amostra_sistematica_2.to_csv("csv/06-amostra_sistematica_2.csv", encoding="iso-8859-1", index=False)
