In [1]:
import pandas as pd
import random
import numpy as np

file_census = "../data_base/census.csv"

dataset = pd.read_csv(file_census)

# Indica o número de Linhas e colunas
dataset.shape

(32561, 15)

In [2]:
# Amostragem por Grupos
populacao = len(dataset)
numero_de_grupos = 10
quantidade_por_grupo = populacao / numero_de_grupos
quantidade_por_grupo


3256.1

In [3]:
# for "_": não cria variável para controlar o for
# iterrows: vai percorrer cada um dos registros da base de dados
grupos = []
id_grupo = 0
contagem = 0
for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > 3256:
        contagem = 0
        id_grupo += 1

print(grupos)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [4]:
# np.unique: Numpy conta quantos valores únicos
np.unique(grupos)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# np.unique: Numpy conta quantos valores únicos
# return_counts: True retorna a contagem de elementos por grupo
np.unique(grupos, return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248],
       dtype=int64))

In [6]:
# comparar o tamanho do grupos com o dataset
# têm de ter o mesmo núm. de linhas para poder juntar ambos sem erro
np.shape(grupos), dataset.shape

((32561,), (32561, 15))

In [7]:
# Concatenar a lista de grupos com o Dataset
# dataframe["nome_coluna"] : 
# Se Não Existir coluna com esse nome # add na última posição # com os dados da lista indicada
# Se Existir atualiza os valores com os dados novos

dataset["grupo"] = grupos
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
0          2174             0             40   United-States   <=50K      0  
1             0             0             13   United-States   <=50K      0  
2             0             0             40   United-States   <=50K      0  
3             0             0             40   United-States   <=50K      0  
4             0             0             40            Cuba   <=50K      0

In [11]:
# escolher um grupo de forma aleatória
random.seed = 1
random.randint(0,9)

7

In [19]:
# capturar um grupo
# value_counts: contagem dos valores e suas quantidades
df_agrupamento = dataset[dataset["grupo"] == 7]
df_agrupamento["grupo"].value_counts()

7    3257
Name: grupo, dtype: int64

In [27]:
def sample_group(dataset, group_quantity):
    population_quantity = len(dataset)
    interval = round(population_quantity / group_quantity)
    # random.seed(1)
    group_list = []
    id_group = 0
    count = 0
    
    for el in dataset.iterrows():
        group_list.append(id_group)
        count += 1
        if count > interval:
            count = 0
            id_group += 1
    
    dataset["grupo"] = group_list
    selected_group_code = random.randint(0, group_quantity)
    selected_group = dataset[dataset["grupo"] == selected_group_code]
    return selected_group      


In [28]:
df_sample_group = sample_group(dataset, 100)
df_sample_group.shape, df_sample_group["grupo"].value_counts()

((327, 16),
 64    327
 Name: grupo, dtype: int64)