In [38]:
import pandas as pd
import random
import numpy as np

file_census = "../data_base/census.csv"

dataset = pd.read_csv(file_census)

# Indica o número de Linhas e colunas
dataset.shape

(32561, 15)

In [39]:
# Amostragem por Grupos
populacao = len(dataset)
numero_de_grupos = 10
quantidade_por_grupo = populacao / numero_de_grupos
quantidade_por_grupo


3256.1

In [40]:
# for "_": não cria variável para controlar o for
# iterrows: vai percorrer cada um dos registros da base de dados
grupos = []
id_grupo = 0
contagem = 0
for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > 3256:
        contagem = 0
        id_grupo += 1

print(grupos)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [41]:
# np.unique: Numpy conta quantos valores únicos
np.unique(grupos)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# np.unique: Numpy conta quantos valores únicos
# return_counts: True retorna a contagem de elementos por grupo
np.unique(grupos, return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248],
       dtype=int64))

In [43]:
# comparar o tamanho do grupos com o dataset
# têm de ter o mesmo núm. de linhas para poder juntar ambos sem erro
np.shape(grupos), dataset.shape

((32561,), (32561, 15))

In [44]:
# Concatenar a lista de grupos com o Dataset
# dataframe["nome_coluna"] : Se não existir coluna com esse nome 
# add na última posição com os dados da lista indicada

dataset["grupo"] = grupos
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
0          2174             0             40   United-States   <=50K      0  
1             0             0             13   United-States   <=50K      0  
2             0             0             40   United-States   <=50K      0  
3             0             0             40   United-States   <=50K      0  
4             0             0             40            Cuba   <=50K      0

In [45]:
# escolher um grupo de forma aleatória
random.seed = 1
random.randint(0,9)

8

In [46]:
# capturar um grupo
df_agrupamento = dataset[dataset["grupo"] == 7]
df_agrupamento.head()

age          workclass  final-weight      education  education-num  \
22799   25   Self-emp-not-inc         21472   Some-college             10   
22800   32            Private         90969      Assoc-voc             11   
22801   26            Private        149734        HS-grad              9   
22802   42            Private         52849   Some-college             10   
22803   39   Self-emp-not-inc        106347   Some-college             10   

            marital-status          occupation    relationship    race  \
22799        Never-married       Other-service   Not-in-family   White   
22800   Married-civ-spouse    Transport-moving         Husband   White   
22801            Separated        Craft-repair       Unmarried   Black   
22802   Married-civ-spouse   Machine-op-inspct         Husband   White   
22803             Divorced               Sales       Unmarried   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
22799   Female             0             0             22   United-States   
22800     Male             0             0             45   United-States   
22801   Female             0          1594             40   United-States   
22802     Male             0             0             40   United-States   
22803     Male             0             0             47   United-States   

       income  grupo  
22799   <=50K      7  
22800    >50K      7  
22801   <=50K      7  
22802   <=50K      7  
22803   <=50K      7

In [56]:
def sample_group(dataset, group_quantity):
    groups_id_list = []
    population_length = len(dataset)
    # Intervalo de elementos em cada grupo
    interval = population_length / group_quantity
    id_group = 0
    count = 0
    
    # for percorre o dataframe e add na lista um número referente ao grupo
    for _ in dataset.iterrows():
        groups_id_list.append(id_group)
        count += 1
        if count > interval:
            count = 0
            id_group += 1
    
    print(np.unique(groups_id_list, return_counts = True))
    print(groups_id_list)

    
    # cria coluna grupo se não existir e atribui os valores
    dataset["group"] = groups_id_list
    # random.seed(1)
    # seleciona um número randômico dentro da quantidade de grupos
    selected_group_code = random.randint(0, group_quantity)

    # seleciona as amostras onde o grupo é igual ao sorteado
    df_sample_group = dataset[dataset["group"] == selected_group_code]
    return df_sample_group

In [58]:
df_sample_group = sample_group(dataset, 10)
df_sample_group.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248],
      dtype=int64))
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

(3257, 17)

In [49]:
np.unique(df_sample_group["group"], return_counts = True)

(array([4], dtype=int64), array([3257], dtype=int64))

In [50]:
df_sample_group.head()

age workclass  final-weight      education  education-num  \
13028   56   Private         98418        HS-grad              9   
13029   30   Private        381153        HS-grad              9   
13030   54   Private        103700        HS-grad              9   
13031   35   Private        298635      Bachelors             13   
13032   32   Private        127895   Some-college             10   

       marital-status         occupation    relationship                 race  \
13028        Divorced   Transport-moving   Not-in-family                White   
13029   Never-married       Craft-repair   Not-in-family                White   
13030         Widowed      Other-service       Unmarried                White   
13031   Never-married              Sales   Not-in-family   Asian-Pac-Islander   
13032   Never-married       Adm-clerical       Own-child                Black   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
13028     Male             0             0             30   United-States   
13029     Male             0             0             40   United-States   
13030   Female             0             0             40   United-States   
13031     Male             0             0             50   United-States   
13032   Female             0             0             40   United-States   

       income  grupo  group  
13028   <=50K      4      4  
13029   <=50K      4      4  
13030   <=50K      4      4  
13031   <=50K      4      4  
13032   <=50K      4      4